name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    if: github.repository == 'timdeschryver/rx-query'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14]

    steps:
      - uses: actions/checkout@v1
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm install
      - name: build
        run: npm run dist:build
      - name: test
        run: npm run test
      # - name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: npx semantic-release
